version: 0.0
os: linux
files:
  - source:
    destination:
hooks:
  BeforeInstall:
    - location:
      timeout:
      runas:
    - location:
      timeout:
      runas:
  ApplicationStop:
    - location:
      timeout:
      runas: